language: python
matrix:
  include:
    - env: TOXENV=py37-graphene-pandas
      python: 3.7
install: pip install .[dev]
script: tox
after_success: coveralls
cache:
  directories:
    - $HOME/.cache/pip
deploy:
  provider: pypi
  user: ig-ksv
  on:
    tags: true